import type { FolderedRoute } from './folders.js';
import { normalizeOpenApiPath, postmanRequestToRouteKey } from './route-id.js';

type PmItem = Record<string, unknown>;

function uniqueSorted<T>(values: T[]): T[] {
  return [...new Set(values)].sort((a, b) => String(a).localeCompare(String(b)));
}

function pathEqual(a: string[], b: string[]): boolean {
  if (a.length !== b.length) return false;
  for (let i = 0; i < a.length; i += 1) {
    if (a[i] !== b[i]) return false;
  }
  return true;
}

function pathIsPrefixOrEqual(short: string[], long: string[]): boolean {
  if (short.length > long.length) return false;
  for (let i = 0; i < short.length; i += 1) {
    if (short[i] !== long[i]) return false;
  }
  return true;
}

/** Compact key for state.json `managedFolders` (e.g. Auth>User>Admin). */
export function managedFolderStateKeyForPath(path: string[]): string {
  return path.filter((s) => s.length > 0).join('>');
}

function titleCaseSegment(seg: string): string {
  const s = seg.trim();
  if (!s) return '';
  return s.charAt(0).toUpperCase() + s.slice(1).toLowerCase();
}

/**
 * Keys used to strip prior pman folder trees from the collection.
 * Includes: state file entries (new `A>B>C` and legacy one-segment) plus
 * per-route aliases for layouts from older releases (root segment, tag-based folders).
 */
function allFolderRemovalKeys(
  stateKeys: string[] | undefined,
  routes: FolderedRoute[],
): string[] {
  const out = new Set<string>();
  for (const raw of stateKeys ?? []) {
    const k = String(raw).trim();
    if (k) out.add(k);
  }
  for (const r of routes) {
    out.add(managedFolderStateKeyForPath(r.folderPath));
    const rootSeg = r.folderPath[0] ?? r.folder;
    if (rootSeg) out.add(rootSeg);
    const tag0 = r.tags[0];
    if (typeof tag0 === 'string' && tag0.trim()) {
      out.add(titleCaseSegment(tag0));
    }
  }
  return uniqueSorted([...out]);
}

function pathMatchesAnyManagedStateKey(
  path: string[],
  statePaths: string[][],
): boolean {
  for (const sp of statePaths) {
    if (pathEqual(path, sp) || pathIsPrefixOrEqual(path, sp) || pathIsPrefixOrEqual(sp, path)) {
      return true;
    }
  }
  return false;
}

function filterOutStateManagedFolderTrees(
  items: unknown[] | undefined,
  stateKeys: string[] | null,
  parentPath: string[],
): unknown[] {
  if (!Array.isArray(items) || !stateKeys || stateKeys.length === 0) {
    return Array.isArray(items) ? [...(items as unknown[])] : [];
  }
  const statePaths = stateKeys.map((k) => k.split('>').filter(Boolean));
  const out: unknown[] = [];
  for (const raw of items) {
    if (!isRecord(raw)) continue;
    const it = raw as PmItem;
    if (it.request && isRecord(it.request)) {
      out.push(it);
      continue;
    }
    if (Array.isArray(it.item)) {
      const name = typeof it.name === 'string' ? it.name : '';
      if (!name) {
        out.push(it);
        continue;
      }
      const herePath = [...parentPath, name];
      if (pathMatchesAnyManagedStateKey(herePath, statePaths)) {
        continue;
      }
      const pman = it._pman;
      const isManaged =
        isRecord(pman) && pman.folderManaged === true
          ? true
          : !isRecord(pman) || pman.folderManaged !== false;
      if (!isManaged) {
        out.push(it);
        continue;
      }
      const nextChildren = filterOutStateManagedFolderTrees(it.item as unknown[], stateKeys, herePath);
      if (nextChildren.length === 0) continue;
      out.push({ ...it, item: nextChildren });
    }
  }
  return out;
}

function buildCreditsText(): string {
  return [
    'Fastify → Postman sync via @st3ix/pman.',
    'Maintainer: St3ix (https://st3ix.net/).',
    'Source of truth: Fastify route schemas (OpenAPI generated by @fastify/swagger).',
  ].join('\n');
}

function buildFolderDescription(folder: string, ops: FolderedRoute[]): string {
  const prefix = ops[0]?.path?.split('/').filter(Boolean)[0];
  const prefixLine = prefix ? `${ops[0].method} /${prefix}/**` : undefined;
  const routeLines = uniqueSorted(ops.map((o) => o.routeKey)).map((rk) => `- ${rk}`);
  const parts = [
    buildCreditsText(),
    '',
    `Folder: ${folder}`,
    ...(prefixLine ? ['', 'Routes (prefix):', `- ${prefixLine}`] : []),
    '',
    'Routes:',
    ...routeLines,
  ];
  return parts.join('\n').trim();
}

function buildCollectionDescription(ops: FolderedRoute[]): string {
  const routeLines = uniqueSorted(ops.map((o) => o.routeKey)).map((rk) => `- ${rk}`);
  return [buildCreditsText(), '', 'Routes:', ...routeLines].join('\n').trim();
}

function isRecord(x: unknown): x is Record<string, unknown> {
  return !!x && typeof x === 'object';
}

function deepClone<T>(x: T): T {
  return structuredClone(x);
}

function flattenRequestItems(
  items: unknown[] | undefined,
  folderPath: string[],
): Array<{ folderPath: string[]; item: PmItem }> {
  if (!items) return [];
  const out: Array<{ folderPath: string[]; item: PmItem }> = [];
  for (const raw of items) {
    if (!isRecord(raw)) continue;
    const it = raw as PmItem;
    if (it.request && isRecord(it.request)) {
      out.push({ folderPath: [...folderPath], item: it });
      continue;
    }
    if (Array.isArray(it.item)) {
      const name = typeof it.name === 'string' ? it.name : 'folder';
      out.push(...flattenRequestItems(it.item as unknown[], [...folderPath, name]));
    }
  }
  return out;
}

function indexExistingByRouteId(
  collection: Record<string, unknown>,
  routeKeyToRouteId: Map<string, string>,
): Map<string, PmItem> {
  const map = new Map<string, PmItem>();
  const rootItems = collection.item;
  if (!Array.isArray(rootItems)) return map;
  for (const { item } of flattenRequestItems(rootItems, [])) {
    const pman = item._pman;
    let routeId: string | undefined;
    if (isRecord(pman) && typeof pman.routeId === 'string') routeId = pman.routeId;
    if (!routeId) {
      const req = item.request as Record<string, unknown> | undefined;
      const method = typeof req?.method === 'string' ? req.method : '';
      const rk = postmanRequestToRouteKey(method, req?.url);
      if (rk) routeId = routeKeyToRouteId.get(rk);
    }
    if (routeId) map.set(routeId, item);
  }
  return map;
}

function flattenGeneratedByRouteKey(collection: Record<string, unknown>): Map<string, PmItem> {
  const map = new Map<string, PmItem>();
  const rootItems = collection.item;
  if (!Array.isArray(rootItems)) return map;
  for (const { item } of flattenRequestItems(rootItems, [])) {
    const req = item.request as Record<string, unknown> | undefined;
    const method = typeof req?.method === 'string' ? req.method : '';
    const rk = postmanRequestToRouteKey(method, req?.url);
    if (rk) map.set(rk, item);
  }
  return map;
}

function defaultPostmanName(op: FolderedRoute): string {
  const p = normalizeOpenApiPath(op.path);
  const segs = p.split('/').filter(Boolean);
  const last = segs[segs.length - 1];
  if (last) {
    return `${op.method} ${last}`;
  }
  return op.routeKey;
}

function buildReqDescription(op: FolderedRoute): string {
  const head =
    typeof op.summary === 'string' && op.summary.trim()
      ? op.summary.trim()
      : 'No summary set for this route.';

  const p = normalizeOpenApiPath(op.path);
  const tags = op.tags.length ? op.tags.join(', ') : '—';
  const body = [
    '---',
    'Generated by @st3ix/pman (do not edit the summary line above if you want stable docs sync).',
    '',
    'Route',
    `- Key: \`${op.routeKey}\``,
    `- Path: \`${p}\``,
    `- Method: \`${op.method}\``,
    `- Tags: ${tags}`,
  ].join('\n');

  return `${head}\n\n${body}`.trim();
}

function shouldPrependSummaryToDescription(summary: string | undefined, description: string): boolean {
  if (typeof summary !== 'string' || !summary.trim()) return false;
  const s = summary.trim();
  const d = description.trim();
  if (!d) return true;
  if (d === s) return false;
  if (d.startsWith(s + '\n')) return false;
  if (d.startsWith(s + '\r\n')) return false;
  return true;
}

function readRequestDescriptionText(item: PmItem | undefined): string | undefined {
  if (!item) return undefined;
  const req = item.request;
  if (!isRecord(req)) return undefined;
  const d = req.description;
  if (typeof d === 'string') return d;
  if (d && typeof d === 'object' && 'content' in d && typeof (d as { content?: unknown }).content === 'string') {
    return String((d as { content: string }).content);
  }
  return undefined;
}

function writeRequestAndItemDescription(item: PmItem, text: string): void {
  // Postman "Docs" for a request is backed by the request's description in Collection v2.1
  // (the converter may leave `item.description` unset).
  const req = (isRecord(item.request) ? (item.request as Record<string, unknown>) : {}) as Record<string, unknown>;
  item.request = { ...req, description: text };
  item.description = text;
}

function mergeRequest(
  existing: PmItem | undefined,
  generated: PmItem,
  op: FolderedRoute,
): PmItem {
  const merged = deepClone(generated) as PmItem;
  const genReq = (merged.request as Record<string, unknown> | undefined) ?? {};
  merged.request = { ...genReq };
  merged.name = typeof op.name === 'string' && op.name.trim() ? op.name.trim() : defaultPostmanName(op);
  if (existing) {
    const oldItemDesc = typeof existing.description === 'string' ? existing.description : '';
    const oldReqDesc = readRequestDescriptionText(existing) ?? '';
    const oldDesc = (oldItemDesc.trim() || oldReqDesc.trim() ? oldItemDesc || oldReqDesc : '').trim();
    if (oldDesc) {
      if (shouldPrependSummaryToDescription(op.summary, oldDesc)) {
        writeRequestAndItemDescription(merged, `${op.summary?.trim() ?? ''}\n\n${oldDesc}`.trim());
      } else {
        writeRequestAndItemDescription(merged, oldDesc);
      }
    } else {
      writeRequestAndItemDescription(merged, buildReqDescription(op));
    }
    if (Array.isArray(existing.event)) merged.event = deepClone(existing.event);
    if (Array.isArray(existing.response) && existing.response.length > 0) {
      merged.response = deepClone(existing.response);
    } else {
      delete merged.response;
    }
  } else {
    delete merged.response;
    writeRequestAndItemDescription(merged, buildReqDescription(op));
  }
  merged._pman = { routeId: op.routeId };
  return merged;
}

type RouteGroup = { path: string[]; items: PmItem[]; ops: FolderedRoute[] };

function prefixMatchesPath(prefix: string[], full: string[]): boolean {
  if (full.length < prefix.length) return false;
  for (let i = 0; i < prefix.length; i += 1) {
    if (full[i] !== prefix[i]) return false;
  }
  return true;
}

type FolderTree = {
  name: string;
  children: Map<string, FolderTree>;
  leafItems: PmItem[];
  leafOps: FolderedRoute[];
};

function getOrCreateChild(tree: FolderTree, name: string): FolderTree {
  const existing = tree.children.get(name);
  if (existing) return existing;
  const next: FolderTree = { name, children: new Map(), leafItems: [], leafOps: [] };
  tree.children.set(name, next);
  return next;
}

function buildFolderTree(groups: Map<string, RouteGroup>): FolderTree {
  const root: FolderTree = { name: '', children: new Map(), leafItems: [], leafOps: [] };
  for (const g of groups.values()) {
    if (!g.path.length) continue;
    let cur = root;
    for (const seg of g.path) {
      cur = getOrCreateChild(cur, seg);
    }
    cur.leafItems.push(...g.items);
    cur.leafOps.push(...g.ops);
  }

  // de-dupe by routeId in case the same op got grouped twice (should not happen)
  for (const t of walkTrees(root)) {
    if (!t.leafItems.length) continue;
    const seen = new Set<string>();
    const items: PmItem[] = [];
    const ops: FolderedRoute[] = [];
    for (let i = 0; i < t.leafItems.length; i += 1) {
      const it = t.leafItems[i];
      const op = t.leafOps[i];
      const id = op.routeId;
      if (seen.has(id)) continue;
      seen.add(id);
      items.push(it);
      ops.push(op);
    }
    t.leafItems = items;
    t.leafOps = ops;
  }
  return root;
}

function* walkTrees(tree: FolderTree): Generator<FolderTree> {
  yield tree;
  for (const c of tree.children.values()) yield* walkTrees(c);
}

function renderFolderTree(node: FolderTree, allRoutes: FolderedRoute[], prefix: string[]): PmItem[] {
  const out: PmItem[] = [];

  const childNames = [...node.children.keys()].sort((a, b) => a.localeCompare(b));
  for (const name of childNames) {
    const child = node.children.get(name);
    if (!child) continue;

    const childPrefix = [...prefix, name];
    const nestedFolders = renderFolderTree(child, allRoutes, childPrefix);
    const directItems = child.leafItems;
    const childItems = [...nestedFolders, ...directItems];
    if (!childItems.length) continue;

    const opsForDesc = allRoutes.filter((r) => prefixMatchesPath(childPrefix, r.folderPath));
    out.push({
      name,
      description: opsForDesc.length ? buildFolderDescription(name, opsForDesc) : buildCreditsText(),
      _pman: { folderManaged: true },
      item: childItems,
    });
  }

  return out;
}

function buildFolderItemsFromGroups(groups: Map<string, RouteGroup>, allRoutes: FolderedRoute[]): PmItem[] {
  const tree = buildFolderTree(groups);
  return renderFolderTree(tree, allRoutes, []);
}

function prunePmanManagedItems(items: unknown[] | undefined): unknown[] {
  if (!Array.isArray(items)) return [];
  const next: unknown[] = [];
  for (const raw of items) {
    if (!isRecord(raw)) continue;
    const it = raw as PmItem;
    if (it.request && isRecord(it.request)) {
      const pman = it._pman;
      if (isRecord(pman) && typeof pman.routeId === 'string') continue;
      next.push(it);
      continue;
    }
    if (Array.isArray(it.item)) {
      const folderName = typeof it.name === 'string' ? it.name : '';
      const pman = it._pman;
      if (folderName && isRecord(pman) && pman.folderManaged === true) continue;
      const prunedChildren = prunePmanManagedItems(it.item as unknown[]);
      if (prunedChildren.length === 0) continue;
      next.push({ ...it, item: prunedChildren });
    }
  }
  return next;
}

export function mergeOpenApiIntoPostmanCollection(args: {
  existing: Record<string, unknown>;
  generated: Record<string, unknown>;
  routes: FolderedRoute[];
  managedFoldersFromState?: string[];
}): Record<string, unknown> {
  const { existing, generated, routes, managedFoldersFromState } = args;
  const routeKeyToRouteId = new Map<string, string>();
  for (const r of routes) routeKeyToRouteId.set(r.routeKey, r.routeId);

  const existingByRouteId = indexExistingByRouteId(existing, routeKeyToRouteId);
  const generatedByKey = flattenGeneratedByRouteKey(generated);
  const byFolder = new Map<string, RouteGroup>();

  for (const op of routes) {
    const gen = generatedByKey.get(op.routeKey);
    if (!gen) continue;
    const prev = existingByRouteId.get(op.routeId);
    const merged = mergeRequest(prev, gen, op);
    const key = op.folderPath.join('>');
    const cur = byFolder.get(key) ?? { path: op.folderPath, items: [], ops: [] };
    cur.items.push(merged);
    cur.ops.push(op);
    byFolder.set(key, cur);
  }

  const out = deepClone(existing) as Record<string, unknown>;
  const info = out.info;
  if (info && typeof info === 'object') {
    const current = (info as Record<string, unknown>).description;
    if (typeof current !== 'string' || current.trim().length === 0) {
      (info as Record<string, unknown>).description = buildCollectionDescription(routes);
    }
  }
  const prevItems = Array.isArray(out.item) ? (out.item as unknown[]) : [];
  const removalKeys = allFolderRemovalKeys(managedFoldersFromState, routes);
  const withoutStateFolders =
    removalKeys.length > 0 ? filterOutStateManagedFolderTrees(prevItems, removalKeys, []) : prevItems;
  const kept = prunePmanManagedItems(withoutStateFolders);
  const fresh = buildFolderItemsFromGroups(byFolder, routes);
  out.item = [...fresh, ...kept];
  return out;
}

export function managedFolderNames(routes: FolderedRoute[]): string[] {
  return uniqueSorted(routes.map((r) => managedFolderStateKeyForPath(r.folderPath)));
}

export function shellCollection(name: string): Record<string, unknown> {
  return {
    info: {
      name,
      schema: 'https://schema.getpostman.com/json/collection/v2.1.0/collection.json',
    },
    item: [],
  };
}

