import type { FolderedRoute } from './folders.js';
import { normalizeOpenApiPath, postmanRequestToRouteKey } from './route-id.js';

type PmItem = Record<string, unknown>;

function uniqueSorted<T>(values: T[]): T[] {
  return [...new Set(values)].sort((a, b) => String(a).localeCompare(String(b)));
}

function buildCreditsText(): string {
  return [
    'Fastify → Postman sync via @st3ix/pman.',
    'Maintainer: St3ix (https://st3ix.net/).',
    'Source of truth: Fastify route schemas (OpenAPI generated by @fastify/swagger).',
  ].join('\n');
}

function buildFolderDescription(folder: string, ops: FolderedRoute[]): string {
  const prefix = ops[0]?.path?.split('/').filter(Boolean)[0];
  const prefixLine = prefix ? `${ops[0].method} /${prefix}/**` : undefined;
  const routeLines = uniqueSorted(ops.map((o) => o.routeKey)).map((rk) => `- ${rk}`);
  const parts = [
    buildCreditsText(),
    '',
    `Folder: ${folder}`,
    ...(prefixLine ? ['', 'Routes (prefix):', `- ${prefixLine}`] : []),
    '',
    'Routes:',
    ...routeLines,
  ];
  return parts.join('\n').trim();
}

function buildCollectionDescription(ops: FolderedRoute[]): string {
  const routeLines = uniqueSorted(ops.map((o) => o.routeKey)).map((rk) => `- ${rk}`);
  return [buildCreditsText(), '', 'Routes:', ...routeLines].join('\n').trim();
}

function isRecord(x: unknown): x is Record<string, unknown> {
  return !!x && typeof x === 'object';
}

function deepClone<T>(x: T): T {
  return structuredClone(x);
}

function flattenRequestItems(
  items: unknown[] | undefined,
  folderPath: string[],
): Array<{ folderPath: string[]; item: PmItem }> {
  if (!items) return [];
  const out: Array<{ folderPath: string[]; item: PmItem }> = [];
  for (const raw of items) {
    if (!isRecord(raw)) continue;
    const it = raw as PmItem;
    if (it.request && isRecord(it.request)) {
      out.push({ folderPath: [...folderPath], item: it });
      continue;
    }
    if (Array.isArray(it.item)) {
      const name = typeof it.name === 'string' ? it.name : 'folder';
      out.push(...flattenRequestItems(it.item as unknown[], [...folderPath, name]));
    }
  }
  return out;
}

function indexExistingByRouteId(
  collection: Record<string, unknown>,
  routeKeyToRouteId: Map<string, string>,
): Map<string, PmItem> {
  const map = new Map<string, PmItem>();
  const rootItems = collection.item;
  if (!Array.isArray(rootItems)) return map;
  for (const { item } of flattenRequestItems(rootItems, [])) {
    const pman = item._pman;
    let routeId: string | undefined;
    if (isRecord(pman) && typeof pman.routeId === 'string') routeId = pman.routeId;
    if (!routeId) {
      const req = item.request as Record<string, unknown> | undefined;
      const method = typeof req?.method === 'string' ? req.method : '';
      const rk = postmanRequestToRouteKey(method, req?.url);
      if (rk) routeId = routeKeyToRouteId.get(rk);
    }
    if (routeId) map.set(routeId, item);
  }
  return map;
}

function flattenGeneratedByRouteKey(collection: Record<string, unknown>): Map<string, PmItem> {
  const map = new Map<string, PmItem>();
  const rootItems = collection.item;
  if (!Array.isArray(rootItems)) return map;
  for (const { item } of flattenRequestItems(rootItems, [])) {
    const req = item.request as Record<string, unknown> | undefined;
    const method = typeof req?.method === 'string' ? req.method : '';
    const rk = postmanRequestToRouteKey(method, req?.url);
    if (rk) map.set(rk, item);
  }
  return map;
}

function defaultPostmanName(op: FolderedRoute): string {
  const p = normalizeOpenApiPath(op.path);
  const segs = p.split('/').filter(Boolean);
  const last = segs[segs.length - 1];
  if (last) {
    return `${op.method} ${last}`;
  }
  return op.routeKey;
}

function buildReqDescription(op: FolderedRoute): string {
  const head =
    typeof op.summary === 'string' && op.summary.trim()
      ? op.summary.trim()
      : 'No summary set for this route.';

  const p = normalizeOpenApiPath(op.path);
  const tags = op.tags.length ? op.tags.join(', ') : '—';
  const body = [
    '---',
    'Generated by @st3ix/pman (do not edit the summary line above if you want stable docs sync).',
    '',
    'Route',
    `- Key: \`${op.routeKey}\``,
    `- Path: \`${p}\``,
    `- Method: \`${op.method}\``,
    `- Tags: ${tags}`,
  ].join('\n');

  return `${head}\n\n${body}`.trim();
}

function shouldPrependSummaryToDescription(summary: string | undefined, description: string): boolean {
  if (typeof summary !== 'string' || !summary.trim()) return false;
  const s = summary.trim();
  const d = description.trim();
  if (!d) return true;
  if (d === s) return false;
  if (d.startsWith(s + '\n')) return false;
  if (d.startsWith(s + '\r\n')) return false;
  return true;
}

function readRequestDescriptionText(item: PmItem | undefined): string | undefined {
  if (!item) return undefined;
  const req = item.request;
  if (!isRecord(req)) return undefined;
  const d = req.description;
  if (typeof d === 'string') return d;
  if (d && typeof d === 'object' && 'content' in d && typeof (d as { content?: unknown }).content === 'string') {
    return String((d as { content: string }).content);
  }
  return undefined;
}

function writeRequestAndItemDescription(item: PmItem, text: string): void {
  // Postman "Docs" for a request is backed by the request's description in Collection v2.1
  // (the converter may leave `item.description` unset).
  const req = (isRecord(item.request) ? (item.request as Record<string, unknown>) : {}) as Record<string, unknown>;
  item.request = { ...req, description: text };
  item.description = text;
}

function mergeRequest(
  existing: PmItem | undefined,
  generated: PmItem,
  op: FolderedRoute,
): PmItem {
  const merged = deepClone(generated) as PmItem;
  const genReq = (merged.request as Record<string, unknown> | undefined) ?? {};
  merged.request = { ...genReq };
  merged.name = typeof op.name === 'string' && op.name.trim() ? op.name.trim() : defaultPostmanName(op);
  if (existing) {
    const oldItemDesc = typeof existing.description === 'string' ? existing.description : '';
    const oldReqDesc = readRequestDescriptionText(existing) ?? '';
    const oldDesc = (oldItemDesc.trim() || oldReqDesc.trim() ? oldItemDesc || oldReqDesc : '').trim();
    if (oldDesc) {
      if (shouldPrependSummaryToDescription(op.summary, oldDesc)) {
        writeRequestAndItemDescription(merged, `${op.summary?.trim() ?? ''}\n\n${oldDesc}`.trim());
      } else {
        writeRequestAndItemDescription(merged, oldDesc);
      }
    } else {
      writeRequestAndItemDescription(merged, buildReqDescription(op));
    }
    if (Array.isArray(existing.event)) merged.event = deepClone(existing.event);
    if (Array.isArray(existing.response) && existing.response.length > 0) {
      merged.response = deepClone(existing.response);
    } else {
      delete merged.response;
    }
  } else {
    delete merged.response;
    writeRequestAndItemDescription(merged, buildReqDescription(op));
  }
  merged._pman = { routeId: op.routeId };
  return merged;
}

function buildFolderItems(
  itemsByFolder: Map<string, PmItem[]>,
  opsByFolder: Map<string, FolderedRoute[]>,
): PmItem[] {
  const folders = [...itemsByFolder.keys()].sort((a, b) => a.localeCompare(b));
  const root: PmItem[] = [];
  for (const name of folders) {
    const items = itemsByFolder.get(name);
    if (!items?.length) continue;
    const ops = opsByFolder.get(name) ?? [];
    root.push({
      name,
      description: ops.length ? buildFolderDescription(name, ops) : buildCreditsText(),
      _pman: { folderManaged: true },
      item: items,
    });
  }
  return root;
}

function prunePmanManagedItems(items: unknown[] | undefined): unknown[] {
  if (!Array.isArray(items)) return [];
  const next: unknown[] = [];
  for (const raw of items) {
    if (!isRecord(raw)) continue;
    const it = raw as PmItem;
    if (it.request && isRecord(it.request)) {
      const pman = it._pman;
      if (isRecord(pman) && typeof pman.routeId === 'string') continue;
      next.push(it);
      continue;
    }
    if (Array.isArray(it.item)) {
      const folderName = typeof it.name === 'string' ? it.name : '';
      const pman = it._pman;
      if (folderName && isRecord(pman) && pman.folderManaged === true) continue;
      const prunedChildren = prunePmanManagedItems(it.item as unknown[]);
      if (prunedChildren.length === 0) continue;
      next.push({ ...it, item: prunedChildren });
    }
  }
  return next;
}

export function mergeOpenApiIntoPostmanCollection(args: {
  existing: Record<string, unknown>;
  generated: Record<string, unknown>;
  routes: FolderedRoute[];
  managedFoldersFromState?: string[];
}): Record<string, unknown> {
  const { existing, generated, routes, managedFoldersFromState } = args;
  const routeKeyToRouteId = new Map<string, string>();
  for (const r of routes) routeKeyToRouteId.set(r.routeKey, r.routeId);

  const existingByRouteId = indexExistingByRouteId(existing, routeKeyToRouteId);
  const generatedByKey = flattenGeneratedByRouteKey(generated);
  const byFolder = new Map<string, PmItem[]>();
  const opsByFolder = new Map<string, FolderedRoute[]>();

  for (const op of routes) {
    const gen = generatedByKey.get(op.routeKey);
    if (!gen) continue;
    const prev = existingByRouteId.get(op.routeId);
    const merged = mergeRequest(prev, gen, op);
    const list = byFolder.get(op.folder) ?? [];
    list.push(merged);
    byFolder.set(op.folder, list);

    const ops = opsByFolder.get(op.folder) ?? [];
    ops.push(op);
    opsByFolder.set(op.folder, ops);
  }

  const out = deepClone(existing) as Record<string, unknown>;
  const info = out.info;
  if (info && typeof info === 'object') {
    const current = (info as Record<string, unknown>).description;
    if (typeof current !== 'string' || current.trim().length === 0) {
      (info as Record<string, unknown>).description = buildCollectionDescription(routes);
    }
  }
  const prevItems = Array.isArray(out.item) ? (out.item as unknown[]) : [];
  const stateNames = Array.isArray(managedFoldersFromState)
    ? new Set(managedFoldersFromState.map((x) => String(x)))
    : null;
  const withoutStateFolders = stateNames
    ? prevItems.filter((raw) => {
        if (!raw || typeof raw !== 'object') return true;
        const it = raw as Record<string, unknown>;
        const name = typeof it.name === 'string' ? it.name : '';
        const isFolder = Array.isArray(it.item);
        if (isFolder && name && stateNames.has(name)) return false;
        return true;
      })
    : prevItems;
  const kept = prunePmanManagedItems(withoutStateFolders);
  const fresh = buildFolderItems(byFolder, opsByFolder);
  out.item = [...fresh, ...kept];
  return out;
}

export function managedFolderNames(routes: FolderedRoute[]): string[] {
  return uniqueSorted(routes.map((r) => r.folder));
}

export function shellCollection(name: string): Record<string, unknown> {
  return {
    info: {
      name,
      schema: 'https://schema.getpostman.com/json/collection/v2.1.0/collection.json',
    },
    item: [],
  };
}

